name: Ejecutar Bot de Mastodon

on:
  schedule:
    # Ejecución programada a las 07:07 UTC (09:07 AM hora peninsular española)
    - cron: '7 7 * * *'
  workflow_dispatch:

jobs:
  run-bot:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Descargar repositorio
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Instalar dependencias
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Ejecutar script del bot
        env:
          MASTODON_TOKEN: ${{ secrets.MASTODON_TOKEN }}
          MASTODON_BASE_URL: ${{ secrets.MASTODON_BASE_URL }}
        run: python bot.py

      - name: Guardar cambios de estado
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add estado.json
          git commit -m "Actualización diaria de estado [skip ci]" || exit 0
          git push
